### ISSUE TITLE
Shaman and Paladin buffing issues

### ISSUE THREAD

**Issue by Kausaliax** [aquietone/aqobot#34]
Shaman will only buff champion.  Will not buff Focus.  

Paladin will not buff Brell's Stalwart Shield.

**Comment by aquietone** [comment]
pushed an update for shaman buff lines.
i don't see any issues with the shm proc buffs with my toons.
my pally seems to cast brells too.

**Comment by Kausaliax** [comment]
I'm not sure what to say.  It's very frustrating.  
![image](https://github.com/user-attachments/assets/84471966-414b-4f89-b039-e91a21daf873)
Still only casted Champion.

My druid casts everything....cleric too.  So confusing

**Comment by aquietone** [comment]
under console flags turn on ability validation. its gonna spam a lot. but it likely has some info about if its at least going into trying to cast it.

**Comment by Kausaliax** [comment]
![image](https://github.com/user-attachments/assets/bcbb3c15-ce40-41b4-a3d5-176d658478bc)

**Comment by Kausaliax** [comment]
![image](https://github.com/user-attachments/assets/b7d770f8-6121-45b6-97e6-1ecfbbc511db)
And then it spams this:
![image](https://github.com/user-attachments/assets/7eec5f05-86d1-4e59-994e-4930a89bc65a)
So a group check needs to be in place to cast or consider buffing panther.

**Comment by Kausaliax** [comment]
Paladin is looking for 
![image](https://github.com/user-attachments/assets/875787ab-19f5-4a6d-b42b-cab53aeddfee)

So they both are not memming the spells needed.

**Comment by Kausaliax** [comment]
Same thing is happening with my shadowknight.  Can't mem spells to self buff.

**Comment by aquietone** [comment]
hm strange. for me it looks like 
![image](https://github.com/user-attachments/assets/4812d650-9e2b-4f14-967e-b3c972cfd92b)


i did run into something else on my shaman though where when it mem'd talisman of wunshi to buff itself (not buff beg), it just kept casting it in a loop. think i fixed that.. maybe get lucky and it happens to relate to your issue too.

**Comment by Kausaliax** [comment]
So on my beastlord the loop is not being able to mem spells it wants to cast.  I will download the latest and give it a try.

Not sure why it's broken for me and not for you, will test and confirm the results here.

**Comment by Kausaliax** [comment]
Ok so it did not correct it, I still get the spam of not being able to mem the spell.  To work around it I just use BYOS and make sure the buffs needed are always memmed.
That being said, I am using the RG mq2 emu build.  Are there any plugins I possibly need that aren't loaded?  I can get a list of the plugins i have for you to look at to see if any are missing that are needed.

**Comment by Kausaliax** [comment]
I have this being spit out by shaman, I clicked off sloth on monk, shaman buffed monk then spits out this Enter and Exit spam in the console.
![image](https://github.com/user-attachments/assets/98c8a985-ca13-4e9d-a615-12ec99d1e6e3)

**Comment by aquietone** [comment]
you got any weird custom ui that wouldn't report properly that spell window is opening or anything else that might throw it off like that?
